### ISSUE TITLE
timestamp problems

### ISSUE THREAD

**Issue by rumcode** [Amay22/NASDAQ-ITCH-5.0-Parser#1]
the specs say length is 6 and is nanoseconds after midnight, but the output is giving 9.  For example a sample record is  [A,? ,  ,517516613, 1177389, B, 100, MSFT, 445000] where ? is not printable. 517516613 is supposed to be the time stamp.  Can you give some clarification on what this time is supposed to be?

**Comment by Amay22** [comment]
@rumcode I really like to see more of this data cause my code may not have bugs.
But I can clarify your doubt. Length is in an integer field that are big-endian or binary encoded numbers. That is not the integer length. It is the byte length i.e. 6 bytes. Hence timestamp is 517516613 (nanoseconds after midnight) and raw data would read something like 000000000000010100010111010100010110011000010011

**Comment by Amay22** [comment]
@rumcode Please close this issue if it has been solved.
